apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-order
  name: mongo-order-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 31998
  selector:
    app: mongo-order
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-order
  name: mongo-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-order
  template:
    metadata:
      labels:
        app: mongo-order
    spec:
      containers:
      - image: mongo:latest
        name: mongo-order
        env:
        - name: MONGO_INITDB_DATABASE
          value: 'order'
        resources:
          limits:
            memory: 1G
            cpu: "1"
