apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
    nodePort: 31997
  selector:
    app: order-ms
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: order-ms-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: order-ms
  template: 
    metadata: 
      labels: 
        app: order-ms
    spec: 
      containers:
      - name: order-ms-container
        image: mathpeixoto/order:0.0.1
        env:
          - name: SPRING_PROFILES_ACTIVE
            value: docker
        ports: 
        - containerPort: 8080