server:
  port: 8082

spring:
  data:
    mongodb:
      uri: mongodb://mongo-shipping-service/shipping

  kafka:
    bootstrap-servers: kafka-broker:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.mpeixoto.shipping.domain.Order
