server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://192.168.49.2:31998/order

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.mpeixoto.order.domain.Order

gateway:
  inventory-url: "http://192.168.49.2:31999/api/products"
  shipping-url: "http://192.168.49.2:31996/api/shipments"
