server:
  port: 8080

spring:
  data:
    mongodb:
      uri: mongodb://mongo-order-service/order

  kafka:
    bootstrap-servers: kafka-broker:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false

    consumer:
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            value:
              default:
                type: com.mpeixoto.order.domain.Order

gateway:
  inventory-url: "http://inventory-service:8081/api/products"
  shipping-url: "http://shipping-service:8082/api/shipments"
