apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-inventory
  name: mongo-inventory-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 31995
  selector:
    app: mongo-inventory
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-inventory
  name: mongo-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-inventory
  template:
    metadata:
      labels:
        app: mongo-inventory
    spec:
      containers:
        - image: mongo:latest
          name: mongo-inventory
          env:
            - name: MONGO_INITDB_DATABASE
              value: 'inventory'
          resources:
            limits:
              memory: 1G
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-order
  name: mongo-order-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 31998
  selector:
    app: mongo-order
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-order
  name: mongo-order
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-order
  template:
    metadata:
      labels:
        app: mongo-order
    spec:
      containers:
        - image: mongo:latest
          name: mongo-order
          env:
            - name: MONGO_INITDB_DATABASE
              value: 'order'
          resources:
            limits:
              memory: 1G
              cpu: "1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-shipping
  name: mongo-shipping-service
spec:
  ports:
    - port: 27017
      protocol: TCP
      targetPort: 27017
      nodePort: 32000
  selector:
    app: mongo-shipping
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-shipping
  name: mongo-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-shipping
  template:
    metadata:
      labels:
        app: mongo-shipping
    spec:
      containers:
        - image: mongo:latest
          name: mongo-shipping
          env:
            - name: MONGO_INITDB_DATABASE
              value: 'shipping'
          resources:
            limits:
              memory: 1G
              cpu: "1"
