apiVersion: v1
kind: Service
metadata:
  name: angular-service
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: angular
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: angular-deployment
spec: 
  replicas: 1
  selector:
    matchLabels:
      app: angular
  template: 
    metadata: 
      labels: 
        app: angular
    spec: 
      containers:
      - name: angular-container
        image: mathpeixoto/frontend:0.0.1
        ports: 
        - containerPort: 80
        resources:
          limits:
            memory: 1G
            cpu: "1"
