services:
  mongo-inventory:
    image: mongo:latest
    container_name: mongo-inventory
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inventory
    ports:
      - "27017:27017"
    networks:
      - inventory-ms-net

  inventory-ms:
    image: inventory-ms
    container_name: inventory-ms
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - inventory-ms-net
    depends_on:
      - "mongo-inventory"

networks:
  inventory-ms-net:
    driver: bridge
