services:
  mongo-inventory:
    image: mongo:latest
    container_name: mongo-inventory-service
    restart: always
    environment:
      MONGO_INITDB_DATABASE: inventory
    ports:
      - "27017:27017"
    networks:
      - inventory-ms-net

  inventory-ms:
    image: mathpeixoto/inventory:0.0.1
    container_name: inventory-ms
    ports:
      - "8081:8081"
    environment:
      - "SPRING_PROFILES_ACTIVE=docker"
    networks:
      - inventory-ms-net
    depends_on:
      - "mongo-inventory"

networks:
  inventory-ms-net:
    driver: bridge
