apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-inventory
  name: mongo-inventory-service
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 32000
  selector:
    app: mongo-inventory
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mongo-inventory
  name: mongo-inventory
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-inventory
  template:
    metadata:
      labels:
        app: mongo-inventory
    spec:
      containers:
      - image: mongo:latest
        name: mongo-inventory
        env:
        - name: MONGO_INITDB_DATABASE
          value: 'inventory'